---
- name: Ensure unzip is installed
  package:
    name: unzip
    state: present

- name: Download Vault
  get_url:
    url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
    dest: /tmp/vault.zip
    mode: '0644'

- name: Unzip Vault
  unarchive:
    src: /tmp/vault.zip
    dest: /usr/local/bin
    remote_src: yes

- name: Download Consul
  get_url:
    url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
    dest: /tmp/consul.zip
    mode: '0644'

- name: Unzip Consul
  unarchive:
    src: /tmp/consul.zip
    dest: /usr/local/bin
    remote_src: yes
