- name: Deploy Vault service file
  template:
    src: service_template.j2
    dest: /etc/systemd/system/{{ vault_service_name }}.service
  vars:
    service_name: "{{ vault_service_name }}"
    exec_path: "{{ vault_exec_path }}"
  notify:
    - Reload systemd

- name: Deploy Consul service file
  template:
    src: service_template.j2
    dest: /etc/systemd/system/{{ consul_service_name }}.service
  vars:
    service_name: "{{ consul_service_name }}"
    exec_path: "{{ consul_exec_path }}"
  notify:
    - Reload systemd

